# Generated by Django 5.0.7 on 2024-11-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_user_ref_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_made_investment',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
