# Generated by Django 5.0.7 on 2024-08-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='plan',
            field=models.CharField(choices=[('Basic', 'Basic'), ('NFT', 'NFT Trading'), ('Crypto', 'Crypto'), ('Stock', 'Stock'), ('Gold', 'Gold')], max_length=20),
        ),
    ]
