# Generated by Django 5.0.7 on 2024-11-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_investment_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='last_profit',
            new_name='next_profit',
        ),
        migrations.AlterField(
            model_name='investment',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('basic', 'Basic'), ('silver', 'Silver'), ('gold', 'Gold'), ('estate', 'Real Estate')], max_length=20),
        ),
    ]
