# Generated by Django 5.0.7 on 2024-11-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_rename_last_profit_investment_next_profit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='is_first',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
