# Generated by Django 5.0.7 on 2024-11-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_investment_is_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='is_first',
        ),
    ]
